name = "WebSockets passthrough"
description = "Implements WebSocket passthrough."
authors = ["<devrel@fastly.com>"]
language = "rust"
manifest_version = 3

[scripts]
  build = "cargo build --profile release"
